baseURL = 'https://nrp.zone'
languageCode = 'en-us'
title = 'nrp.zone'
copyright = "Copyright ©️ 2024-2025, Nathan Ross Powell"
theme = 'risotto'
pagination.pagerSize = 3
DefaultContentLanguage = "en-us"
enableInlineShortcodes = true

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[params]
noindex = false

[params.theme]
palette = "nrp"

# Sidebar: about/bio
[params.about]
title = "nrp zone"
description = "A blog by the gamedev [Nathan Ross Powell](https://nathanrosspowell.github.io). They mainly focus on gameplay, network and engine programming."
# unicode/emoji logo:
logo = "🦥"
# or use an image:
#logo_image = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub Profile"
url = "https://github.com/nathanrosspowell"

[[params.socialLinks]]
icon = "fa-brands fa-bluesky"
title = "Bluesky Profile"
url = "https://bsky.app/profile/nrp.zone"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn Profile"
url = "https://www.linkedin.com/in/nathanrosspowell/"

[[params.socialLinks]]
icon = "fa-solid fa-rss"
title = "Blog RSS"
url = "https://nrp.zone/index.xml"

[[params.socialLinks]]
icon = "fa-solid fa-link"
title = "Project Links"
url = "https://nathanrosspowell.github.io/"


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

  [markup.highlight]
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    noClasses = true
    style = 'dracula'
    tabWidth = 4

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true